import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex items-center justify-center flex-col bg-black min-h-[820px]">
          <div className="w-[500px] min-h-[820px] border-4 border-yellow-500 mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
