import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex bg-black min-h-screen">
        <div className="w-[500px] min-h-[820px] border-4 border-gray-200 mx-auto bg-gray-900 rounded-lg shadow-lg transition-all duration-300 hover:border-gray-200 hover:scale-105">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
